name: deploy-aws
on: [push]

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ASIAQW2PALX5EDAKZJF2
          aws-secret-access-key: oyDjmA4w+OG5UxBRBnAU2CZVW20PA1INGUDG+K8w
          aws-session-token: FwoGZXIvYXdzELb//////////wEaDD2X9NiZDckcHbrLiiK+AfzMMHQFYVtus1hv7mk3VVlIlAxejEK5jSA3FwebB8HyuWwg5pE40AtyzJrRqYnBYxd7EwKqx4qnH3awqaPzEa3MoJUOBSfqQH1mTW6hwcE55Kr5FumXHHZgPX3M9LOSM1W1ey8tVnIApkXDBur/Ds0fe5OM5vknM37Gd6vevqdkhuf0T9/VG6FJKQ5Lrhqtcp0fOacm4MV3RlNMht2W5WY7hZyhS2JsiYR22ahdvr0u7Lvf1SQ4tvdVozbBozIo2Y61qgYyLcDVL+rE4FTFnP3xwIxCs1XzTopDB2/22IRRttnEBF16j1kuqGRmD0RUh//MGQ==
          aws-region: us-east-1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Upload to S3
        run: |
          mkdir deployment
          rsync -Rr . deployment
          zip -r deployment.zip deployment
          aws s3 cp deployment.zip s3://${{ secrets.S3_BUCKET }}/

      - name: Create deployment
        run: |
          aws deploy create-deployment --application-name codedeploy-example \
              --deployment-config-name CodeDeployDefault.OneAtATime \
              --deployment-group-name DEPLOYMENT_GROUP \
              --s3-location bucket=${{ secrets.S3_BUCKET }},bundleType=zip,key=deployment.zip
